### ISSUE TITLE
takeSingleCameraImage() should redirect user to App settings when permission is Locked

### ISSUE THREAD

**Issue by MajdHojera** [NicosNicolaou16/ImagePickerAndroid#7]
When user declines the camera permission multiple times, the permission becomes blocked, means the permission dialog launcher just does Nothing. In this case, it is typical to redirect the user to the app settings.

Other solution for this issue is to provide the User of the library and permissionLockedCallback so they can show their own dialog or redirect to the settings.

**Comment by NicosNicolaou16** [comment]
Hello @MajdHojera, thank you for your feedback. Check the next version when it is released!

**Comment by NicosNicolaou16** [comment]
Closed this issue as it is solved.
